name = input ("이름을 입력하세요: ")
studentnum = input ("학번을 입력하세요: ")
department = input ("학과를 입력하세요: ")
grade = input("학년을 입력하세요: ")

print ("<출력>")
print("이름: " + name)
print("학번: " + studentnum)
print("학과: "+ department)
print("학년: "+grade)